route:
  receiver: 'telegram-bot'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'telegram-bot'
    telegram_configs:
      - bot_token: 'TOKEN_PLACEHOLDER'
        chat_id: CHAT_ID_PLACEHOLDER
        message: '{{ range .Alerts }} <b>{{ .Annotations.summary }}</b>{{ end }}'
        parse_mode: 'HTML'