version: '3.8'

services:
  nlp-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis-db
    environment:
      - PYTHONUNBUFFERED=1

  redis-db:
    image: redis:alpine
    ports:
      - "6379:6379"
